### ISSUE TITLE
Trouble with createPredictionModel.py

### ISSUE THREAD

**Issue by dallas-cottrell** [kjaisingh/march-madness-2019#2]
Hi, this is my first Python project and I am getting this error below when I run thecreatePredictionModel.py:

Any assistance you can offer is greatly appreciated.

Dallass-MacBook-Pro:march-madness-2019 DallasCottrell$ python createPredictionModel.py
Training Logistic Regression model...
/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
Training Random Forest model...
Training Naive Bayes model...
Training Neural Network model...
Using TensorFlow backend.
Traceback (most recent call last):
  File "createPredictionModel.py", line 82, in <module>
    classifier_nn = Sequential()
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/engine/sequential.py", line 87, in __init__
    super(Sequential, self).__init__(name=name)
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 96, in __init__
    self._init_subclassed_network(**kwargs)
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 294, in _init_subclassed_network
    self._base_init(name=name)
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 109, in _base_init
    name = prefix + '_' + str(K.get_uid(prefix))
  File "/Users/DallasCottrell/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

**Comment by kjaisingh** [comment]
Hi, I don't think that you have updated your Keras/Tensorflow to the latest version.
